// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Local SQLite dev uses schema.dev.prisma; Vercel PostgreSQL uses schema.prisma
const isLocalSqlite = process.env["DATABASE_URL"]?.startsWith("file:");

export default defineConfig({
  schema: isLocalSqlite ? "prisma/schema.dev.prisma" : "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
